const phrases = {
  1: 'El primero de la tanda, el uno',
  2: 'El patito solo en el agua, el dos',
  3: 'La Santísima Trinidad, el tres',
  4: 'Como las patas del gato, el cuatro',
  5: 'Los dedos de la mano, el cinco',
  6: 'Media docena de huevos, el seis',
  7: 'El hacha de mi abuelo, el siete',
  8: 'Comiendo bizcocho, el ocho',
  9: 'El rabo del chancho, el nueve',
  10: 'Diez deditos, el diez',
  11: 'Las canillas de mi abuela, el once',
  12: 'Docena de huevos, el doce',
  13: 'Que no nos traiga mala suerte, el trece',
  14: 'Limpio y esperando que paguen, el catorce',
  15: 'La quinceañera del barrio, el quince',
  16: 'La hora del café, el dieciséis',
  17: 'Se mete la suerte, el diecisiete',
  18: 'El mayor de edad, el dieciocho',
  19: 'Falta uno para los veinte, el diecinueve',
  20: 'Pato con huevo, el veinte',
  21: 'El veintiuno',
  22: 'Los dos patitos en el agua, el veintidós',
  23: 'El veintitrés',
  24: 'Nochebuena, el veinticuatro',
  25: 'Nació el Niño Dios, el veinticinco',
  26: 'El veintiséis',
  27: 'El veintisiete',
  28: 'El veintiocho',
  29: 'El veintinueve',
  30: 'El treinta',
  31: 'El vacilón continúa, el treinta y uno',
  32: 'El treinta y dos',
  33: 'La edad de Cristo, el treinta y tres',
  34: 'La cabeza del gato, el treinta y cuatro',
  35: 'El loquillo del pueblo, el treinta y cinco',
  36: 'Búsquelo bien, el treinta y seis',
  37: 'El treinta y siete',
  38: 'El treinta y ocho',
  39: 'El treinta y nueve',
  40: 'El cuarenta',
  41: 'Cae uno por uno, el cuarenta y uno',
  42: 'El cuarenta y dos',
  43: 'El cuarenta y tres',
  44: 'Las dos sillitas de la escuela, el cuarenta y cuatro',
  45: 'A medio camino, el cuarenta y cinco',
  46: 'Pura vida mae, el cuarenta y seis',
  47: 'El cuarenta y siete',
  48: 'El viejo chocho, el cuarenta y ocho',
  49: 'El cuarenta y nueve',
  50: 'La media teja, el cincuenta',
  51: 'El cincuenta y uno',
  52: 'Sin codos, el cincuenta y dos',
  53: 'El cincuenta y tres',
  54: 'Ojo con el gato, el cincuenta y cuatro',
  55: 'Pegando un brinco, el cincuenta y cinco',
  56: 'El cincuenta y seis',
  57: 'El cincuenta y siete',
  58: 'El cincuenta y ocho',
  59: 'Pero mira como se mueve, el cincuenta y nueve',
  60: 'Venga y se sienta, el sesenta',
  61: 'El sesenta y uno',
  62: 'El sesenta y dos',
  63: 'El sesenta y tres',
  64: 'El sesenta y cuatro',
  65: 'Brinquito de alegría, el sesenta y cinco',
  66: 'Dos monjitas, el sesenta y seis',
  67: 'El sesenta y siete',
  68: 'Que sirvan el bizcocho, el sesenta y ocho',
  69: 'Arriba y abajo, el sesenta y nueve',
  70: 'El setenta',
  71: 'La bruja, el setenta y uno',
  72: 'Los dos de la fila, el setenta y dos',
  73: 'El setenta y tres',
  74: 'El setenta y cuatro',
  75: 'El que limpia el cartón, el setenta y cinco',
  76: 'El setenta y seis',
  77: 'Las dos hachas para la leña, el setenta y siete',
  78: 'El setenta y ocho',
  79: 'El setenta y nueve',
  80: 'La gente está atenta, el ochenta',
  81: 'El ochenta y uno',
  82: 'Los dos amigos de siempre, el ochenta y dos',
  83: 'El ochenta y tres',
  84: 'El ochenta y cuatro',
  85: 'El último brinco, el ochenta y cinco',
  86: 'El ochenta y seis',
  87: 'El ochenta y siete',
  88: 'El ochenta y ocho',
  89: 'El ochenta y nueve',
  90: 'El tata del bingo, el noventa',
};

let total = 0;
for (let i = 1; i <= 90; i++) {
  const len = phrases[i].length;
  total += len;
  console.log(i + ': ' + len + ' chars - "' + phrases[i] + '"');
}
console.log('');
console.log('Total caracteres necesarios: ' + total);
console.log('Creditos disponibles:        4847');
console.log('Diferencia:                  ' + (4847 - total));
console.log(total <= 4847 ? 'CABEN en la cuota' : 'NO CABEN - faltan ' + (total - 4847) + ' caracteres');
